import = [
  "/home/david/.dotfiles/alacritty/catppuccin/catppuccin-macchiato.toml",
]

[env]
TERM = "xterm-256color"

[font]
size = 15.0

[font.bold]
family = "MonoLisa"
style = "Bold"

[font.bold_italic]
family = "MonoLisa"
style = "Medium Italic"

[font.italic]
family = "MonoLisa"
style = "Italic"

[font.normal]
family = "MonoLisa"
style = "Light"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "PageUp"
mode = "~Alt"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "PageDown"
mode = "~Alt"

[window]
decorations = "none"
opacity = 0.9
startup_mode = "Maximized"

[window.padding]
x = 10
y = 6
