#!/usr/bin/env zsh

PLUGIN_DIR="$CONFIG_DIR/plugins"
FONT_FACE="MonoLisa"
ICON_FONT="Hack Nerd Font Mono"

sketchybar --bar \
    height=32 \
    color=0x00000000 \
    margin=0 \
    padding_left=24 \
    padding_right=24 \
    sticky=true \
    y_offset=4

sketchybar --default \
    background.color=0xB3494d64 \
    background.corner_radius=5 \
    background.padding_right=5 \
    background.height=30 \
    icon.font="$ICON_FONT:Regular:18.0" \
    icon.padding_left=8 \
    icon.padding_right=8 \
    label.font="$FONT_FACE:Medium:13.0" \
    label.color=0xffcad3f5 \
    label.y_offset=0 \
    label.padding_left=0 \
    label.padding_right=6

sketchybar --add item current_space left \
    --set current_space \
    background.color=0xfff5a97f \
    icon.color=0xff24273a \
    label.font="$FONT_FACE:Medium:14.0" \
    label.drawing=off \
    script="$PLUGIN_DIR/current_space.sh" \
    --subscribe current_space space_change mouse.clicked

sketchybar --add item front_app left \
    --set front_app \
    background.color=0xffa6da95 \
    background.padding_left=0 \
    background.padding_right=0 \
    icon.y_offset=1 \
    icon.color=0xff24273a \
    label.drawing=no \
    script="$PLUGIN_DIR/front_app.sh" \
    --add item front_app.separator left \
    --set front_app.separator \
    background.color=0x00000000 \
    background.padding_left=-3 \
    icon= \
    icon.color=0xffa6da95 \
    icon.font="$FONT_FACE:Bold:20.0" \
    icon.padding_left=0 \
    icon.padding_right=0 \
    icon.y_offset=1 \
    label.drawing=no \
    --add item front_app.name left \
    --set front_app.name \
    background.color=0x00000000 \
    background.padding_right=0 \
    icon.drawing=off \
    label.font="$FONT_FACE:Bold:13.0" \
    label.drawing=yes

sketchybar --add bracket front_app_bracket \
    front_app \
    front_app.separator \
    front_app.name \
    --subscribe front_app front_app_switched

sketchybar --add item clock right \
    --set clock \
    icon=󰃰 \
    icon.color=0xffed8796 \
    update_freq=10 \
    script="$PLUGIN_DIR/clock.sh"

sketchybar --add item battery right \
    --set battery \
    update_freq=20 \
    script="$PLUGIN_DIR/battery.sh"

sketchybar --add item volume right \
    --set volume \
    icon.color=0xff8aadf4 \
    label.drawing=true \
    script="$PLUGIN_DIR/volume.sh" \
    --subscribe volume volume_change

# osascript -e 'quit app "Rectangle"'
# open -a Rectangle

##### Finalizing Setup #####
sketchybar --update
sketchybar --trigger space_change
